name: Security Checks

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Building Docker Node-Goat Image
        run: docker compose build

      - name: Launching the app
        run: docker compose up --detach

      - name: Wait for app to be ready
        run: |
          timeout 60s bash -c 'until curl -s localhost:4000; do sleep 5; done'
          echo "Aplicação Node-Goat disponível na porta 4000"

      - name: Change permissions for ZAP
        run: chmod -R 777 ${{ github.workspace }}

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "http://localhost:4000"  # A URL da sua aplicação Node-Goat
          fail_action: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: "Security Scan Report"
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          allow_issue_writing: true
          artifact_name: zap_scan_report  # Nome do artefato
          cmd_options: "-J report_json.json -w report_md.md -r /zap/wrk/report_html.html"  # Gerar os relatórios

      - name: Upload ZAP Report Manualmente
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_report  # Nome simples e válido
          path: /zap/wrk/report_html.html  # Caminho para o relatório HTML gerado
